export const destinations = [
  {
    id: 'london',
    name: 'Londra',
    country: 'UK',
    lat: 51.5074,
    lng: -0.1278,
    vibe: 'city',
    tagline: 'Hotel da €29/notte',
    price: 29,
    stars: 4,
    rating: 8.4,
    reviews: 15420,
    distance: 0.6,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Central hotels near theaters, Hyde Park and Buckingham Palace.'
  },
  {
    id: 'paris',
    name: 'Parigi',
    country: 'Francia',
    lat: 48.8566,
    lng: 2.3522,
    vibe: 'city',
    tagline: 'Hotel da €45/notte',
    price: 45,
    stars: 5,
    rating: 8.7,
    reviews: 12380,
    distance: 1.2,
    amenities: ['WiFi', 'Spa', 'Metro'],
    description: 'Elegant stays near the Eiffel Tower and the Louvre.'
  },
  {
    id: 'rome',
    name: 'Roma',
    country: 'Italia',
    lat: 41.9028,
    lng: 12.4964,
    vibe: 'city',
    tagline: 'Hotel da €39/notte',
    price: 39,
    stars: 4,
    rating: 8.2,
    reviews: 9800,
    distance: 1.5,
    amenities: ['WiFi', 'Breakfast', 'Pool'],
    description: 'Charming hotels a short walk from the Colosseum and Vatican.'
  },
  {
    id: 'barcelona',
    name: 'Barcellona',
    country: 'Spagna',
    lat: 41.3851,
    lng: 2.1734,
    vibe: 'beach',
    tagline: 'Hotel da €35/notte',
    price: 35,
    stars: 4,
    rating: 8.1,
    reviews: 8700,
    distance: 2.0,
    amenities: ['WiFi', 'Pool', 'Metro'],
    description: 'Vibrant stays near Sagrada Família and Las Ramblas.'
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Paesi Bassi',
    lat: 52.3676,
    lng: 4.9041,
    vibe: 'city',
    tagline: 'Hotel da €49/notte',
    price: 49,
    stars: 4,
    rating: 8.5,
    reviews: 7200,
    distance: 1.0,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Canal-side hotels close to museums and the city center.'
  },
  {
    id: 'berlin',
    name: 'Berlino',
    country: 'Germania',
    lat: 52.52,
    lng: 13.405,
    vibe: 'city',
    tagline: 'Hotel da €29/notte',
    price: 29,
    stars: 3,
    rating: 7.9,
    reviews: 10500,
    distance: 2.5,
    amenities: ['WiFi', 'Parking', 'Metro'],
    description: 'Trendy stays near Brandenburg Gate and Museum Island.'
  },
  {
    id: 'sardinia',
    name: 'Sardegna',
    country: 'Italia',
    lat: 39.8,
    lng: 9.0,
    vibe: 'beach',
    tagline: 'Hotel da €55/notte',
    price: 55,
    stars: 4,
    rating: 8.5,
    reviews: 6200,
    distance: 12.0,
    amenities: ['WiFi', 'Pool', 'Parking'],
    description: 'Spiagge, mare cristallino e strutture per famiglie.'
  },
  {
    id: 'puglia',
    name: 'Puglia',
    country: 'Italia',
    lat: 40.8,
    lng: 17.1,
    vibe: 'beach',
    tagline: 'Hotel da €42/notte',
    price: 42,
    stars: 3,
    rating: 8.3,
    reviews: 5400,
    distance: 8.0,
    amenities: ['WiFi', 'Breakfast', 'Parking'],
    description: 'Bassa costiera, trulli, mare e buona cucina a prezzi contenuti.'
  },
  {
    id: 'tuscany',
    name: 'Toscana',
    country: 'Italia',
    lat: 43.77,
    lng: 11.25,
    vibe: 'countryside',
    tagline: 'Hotel da €38/notte',
    price: 38,
    stars: 3,
    rating: 8.6,
    reviews: 7100,
    distance: 5.0,
    amenities: ['WiFi', 'Breakfast', 'Pool'],
    description: 'Colline, vigneti e borghi medievali per un weekend rilassante.'
  },
  {
    id: 'french-riviera',
    name: 'Costa Azzurra',
    country: 'Francia',
    lat: 43.7,
    lng: 7.2,
    vibe: 'beach',
    tagline: 'Hotel da €70/notte',
    price: 70,
    stars: 4,
    rating: 8.2,
    reviews: 4800,
    distance: 3.0,
    amenities: ['WiFi', 'Spa', 'Metro'],
    description: 'Nizza, Cannes e Villefranche: mare e stile francese.'
  },
  {
    id: 'milan',
    name: 'Milano',
    country: 'Italia',
    lat: 45.46,
    lng: 9.19,
    vibe: 'city',
    tagline: 'Hotel da €50/notte',
    price: 50,
    stars: 4,
    rating: 8.1,
    reviews: 8900,
    distance: 1.0,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Business, moda e movida a due passi dal Duomo.'
  },
  {
    id: 'venice',
    name: 'Venezia',
    country: 'Italia',
    lat: 45.43,
    lng: 12.32,
    vibe: 'city',
    tagline: 'Hotel da €60/notte',
    price: 60,
    stars: 5,
    rating: 8.4,
    reviews: 8100,
    distance: 0.8,
    amenities: ['WiFi', 'Spa', 'Metro'],
    description: 'Canali, gondole e hotel romantici in centro.'
  },
  {
    id: 'alps',
    name: 'Alpi',
    country: 'Italia',
    lat: 46.5,
    lng: 11.3,
    vibe: 'mountain',
    tagline: 'Hotel da €45/notte',
    price: 45,
    stars: 3,
    rating: 8.7,
    reviews: 4300,
    distance: 4.0,
    amenities: ['WiFi', 'Spa', 'Parking'],
    description: 'Montagna, trekking, wellness e sport invernali.'
  },
  {
    id: 'liguria',
    name: 'Liguria',
    country: 'Italia',
    lat: 44.3,
    lng: 9.2,
    vibe: 'beach',
    tagline: 'Hotel da €48/notte',
    price: 48,
    stars: 3,
    rating: 8.4,
    reviews: 5100,
    distance: 6.0,
    amenities: ['WiFi', 'Breakfast', 'Pool'],
    description: 'Cinque Terre, Porto Venere e golfi incantevoli.'
  },
  {
    id: 'ibiza',
    name: 'Ibiza',
    country: 'Spagna',
    lat: 38.98,
    lng: 1.43,
    vibe: 'beach',
    tagline: 'Hotel da €62/notte',
    price: 62,
    stars: 4,
    rating: 8.2,
    reviews: 4300,
    distance: 9.0,
    amenities: ['WiFi', 'Pool', 'Parking'],
    description: 'Movida, spiagge bianche e tramonti da sogno.'
  },
  {
    id: 'mallorca',
    name: 'Maiorca',
    country: 'Spagna',
    lat: 39.57,
    lng: 2.65,
    vibe: 'beach',
    tagline: 'Hotel da €48/notte',
    price: 48,
    stars: 3,
    rating: 8.3,
    reviews: 5200,
    distance: 8.0,
    amenities: ['WiFi', 'Breakfast', 'Pool'],
    description: 'Mare cristallino, borghi e vacanze per famiglie.'
  },
  {
    id: 'mykonos',
    name: 'Mykonos',
    country: 'Grecia',
    lat: 37.45,
    lng: 25.35,
    vibe: 'beach',
    tagline: 'Hotel da €80/notte',
    price: 80,
    stars: 4,
    rating: 8.6,
    reviews: 3900,
    distance: 7.0,
    amenities: ['WiFi', 'Pool', 'Spa'],
    description: 'Isole Cicladi, case bianche e vita mondana.'
  },
  {
    id: 'santorini',
    name: 'Santorini',
    country: 'Grecia',
    lat: 36.39,
    lng: 25.46,
    vibe: 'beach',
    tagline: 'Hotel da €95/notte',
    price: 95,
    stars: 5,
    rating: 8.7,
    reviews: 3600,
    distance: 6.0,
    amenities: ['WiFi', 'Spa', 'Pool'],
    description: 'Tramonti iconici, vulcano e suite con vista mare.'
  },
  {
    id: 'malta',
    name: 'Malta',
    country: 'Malta',
    lat: 35.94,
    lng: 14.37,
    vibe: 'beach',
    tagline: 'Hotel da €46/notte',
    price: 46,
    stars: 3,
    rating: 8.3,
    reviews: 4700,
    distance: 5.0,
    amenities: ['WiFi', 'Breakfast', 'Pool'],
    description: 'Storia, spiagge e sole quasi tutto l’anno.'
  },
  {
    id: 'sicily',
    name: 'Sicilia',
    country: 'Italia',
    lat: 37.6,
    lng: 14.0,
    vibe: 'beach',
    tagline: 'Hotel da €41/notte',
    price: 41,
    stars: 3,
    rating: 8.4,
    reviews: 5800,
    distance: 7.0,
    amenities: ['WiFi', 'Breakfast', 'Parking'],
    description: 'Mare, vulcani, barocchi e cucina strepitosa.'
  },
  {
    id: 'croatia',
    name: 'Croazia',
    country: 'Croazia',
    lat: 43.5,
    lng: 16.4,
    vibe: 'beach',
    tagline: 'Hotel da €43/notte',
    price: 43,
    stars: 3,
    rating: 8.2,
    reviews: 4500,
    distance: 8.0,
    amenities: ['WiFi', 'Pool', 'Parking'],
    description: 'Spalato, Dubrovnik e isole dalla costa dalmata.'
  },
  {
    id: 'budapest',
    name: 'Budapest',
    country: 'Ungheria',
    lat: 47.49,
    lng: 19.04,
    vibe: 'city',
    tagline: 'Hotel da €33/notte',
    price: 33,
    stars: 3,
    rating: 8.2,
    reviews: 6200,
    distance: 1.2,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Terme, Danubio e architettura imperdibile.'
  },
  {
    id: 'prague',
    name: 'Praga',
    country: 'Repubblica Ceca',
    lat: 50.07,
    lng: 14.43,
    vibe: 'city',
    tagline: 'Hotel da €36/notte',
    price: 36,
    stars: 3,
    rating: 8.3,
    reviews: 6800,
    distance: 1.0,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Castello, ponte Carlo e atmosfera da fiaba.'
  },
  {
    id: 'vienna',
    name: 'Vienna',
    country: 'Austria',
    lat: 48.20,
    lng: 16.37,
    vibe: 'city',
    tagline: 'Hotel da €44/notte',
    price: 44,
    stars: 4,
    rating: 8.5,
    reviews: 5900,
    distance: 1.3,
    amenities: ['WiFi', 'Spa', 'Metro'],
    description: 'Caffè, musica e palazzi in centro storico.'
  },
  {
    id: 'lisbon',
    name: 'Lisbona',
    country: 'Portogallo',
    lat: 38.72,
    lng: -9.13,
    vibe: 'city',
    tagline: 'Hotel da €40/notte',
    price: 40,
    stars: 3,
    rating: 8.4,
    reviews: 6400,
    distance: 1.5,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Tram, azulejos, fado e vista sull’Atlantico.'
  },
  {
    id: 'porto',
    name: 'Porto',
    country: 'Portogallo',
    lat: 41.15,
    lng: -8.61,
    vibe: 'city',
    tagline: 'Hotel da €37/notte',
    price: 37,
    stars: 3,
    rating: 8.4,
    reviews: 5500,
    distance: 1.2,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Ponte Dom Luís, vino Porto e Ribeira romantica.'
  }
]
