export const destinations = [
  {
    id: 'london',
    name: 'London',
    country: 'UK',
    lat: 51.5074,
    lng: -0.1278,
    tagline: 'Hotels from €29/night',
    price: 29,
    stars: 4,
    rating: 8.4,
    reviews: 15420,
    distance: 0.6,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Central hotels near theaters, Hyde Park and Buckingham Palace.'
  },
  {
    id: 'paris',
    name: 'Paris',
    country: 'France',
    lat: 48.8566,
    lng: 2.3522,
    tagline: 'Hotels from €45/night',
    price: 45,
    stars: 5,
    rating: 8.7,
    reviews: 12380,
    distance: 1.2,
    amenities: ['WiFi', 'Spa', 'Metro'],
    description: 'Elegant stays near the Eiffel Tower and the Louvre.'
  },
  {
    id: 'rome',
    name: 'Rome',
    country: 'Italy',
    lat: 41.9028,
    lng: 12.4964,
    tagline: 'Hotels from €39/night',
    price: 39,
    stars: 4,
    rating: 8.2,
    reviews: 9800,
    distance: 1.5,
    amenities: ['WiFi', 'Breakfast', 'Pool'],
    description: 'Charming hotels a short walk from the Colosseum and Vatican.'
  },
  {
    id: 'barcelona',
    name: 'Barcelona',
    country: 'Spain',
    lat: 41.3851,
    lng: 2.1734,
    tagline: 'Hotels from €35/night',
    price: 35,
    stars: 4,
    rating: 8.1,
    reviews: 8700,
    distance: 2.0,
    amenities: ['WiFi', 'Pool', 'Metro'],
    description: 'Vibrant stays near Sagrada Família and Las Ramblas.'
  },
  {
    id: 'amsterdam',
    name: 'Amsterdam',
    country: 'Netherlands',
    lat: 52.3676,
    lng: 4.9041,
    tagline: 'Hotels from €49/night',
    price: 49,
    stars: 4,
    rating: 8.5,
    reviews: 7200,
    distance: 1.0,
    amenities: ['WiFi', 'Breakfast', 'Metro'],
    description: 'Canal-side hotels close to museums and the city center.'
  },
  {
    id: 'berlin',
    name: 'Berlin',
    country: 'Germany',
    lat: 52.52,
    lng: 13.405,
    tagline: 'Hotels from €29/night',
    price: 29,
    stars: 3,
    rating: 7.9,
    reviews: 10500,
    distance: 2.5,
    amenities: ['WiFi', 'Parking', 'Metro'],
    description: 'Trendy stays near Brandenburg Gate and Museum Island.'
  }
]
